services:
  apache-nifi:
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=nifi
      - SINGLE_USER_CREDENTIALS_PASSWORD=HGd15bvfv8744ghbdhgdv7895agqERAo
      - TZ=America/Sao_Paulo
    image: apache/nifi:2.0.0
    container_name: apache-nifi
    ports:
      - "8443:8443"
    deploy:
      resources:
        limits:
          cpus: "0.95"
          memory: 4G
    restart: on-failure
    volumes: 
      - nifi-python:/opt/nifi/nifi-current/python_extensions
      - nifi-conf:/opt/nifi/nifi-current/conf
      - nifi-content:/opt/nifi/nifi-current/content_repository
      - nifi-database:/opt/nifi/nifi-current/database_repository
      - nifi-flowfile:/opt/nifi/nifi-current/flowfile_repository
      - nifi-logs:/opt/nifi/nifi-current/logs
      - nifi-nar:/opt/nifi/nifi-current/nar_extensions
      - nifi-provenance:/opt/nifi/nifi-current/provenance_repository
      - nifi-state:/opt/nifi/nifi-current/state
      - ./nifi/jdbc:/home/nifi/jdbc:rw
      - ./nifi/mock:/home/nifi/mock:rw
    networks:
      - rede-arquivos-parquet
  mysql:
    depends_on:
      - apache-nifi
    image: mysql:5.7.40
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/dados_mysql:/var/lib/mysql:rw
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: "0.95"
          memory: 4G
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=W45uE75hQ15Oa
      - TZ=America/Sao_Paulo
    healthcheck:
      test: mysqladmin ping -h mysql -u root -pW45uE75hQ15Oa || exit 1
      interval: 30s
      timeout: 20s
      retries: 5
    networks:
      - rede-arquivos-parquet
  minio-s3:
    depends_on:
      - apache-nifi
    hostname: minio-s3
    container_name: minio-s3
    image: bitnami/minio:2023
    ports: 
      - "9000:9000"
      - "9001:9001"
    environment: 
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=eO3RNPcKgWInlzPJuI08
      - TZ=America/Sao_Paulo
    deploy:
      resources:
        limits:
          memory: 2G
    restart: always
    volumes: 
      - minio_data:/data
      - minio_certs:/certs
    networks:
      - rede-arquivos-parquet

volumes:
  nifi-python:
  nifi-conf:
  nifi-content:
  nifi-database:
  nifi-flowfile:
  nifi-logs:
  nifi-nar:
  nifi-provenance:
  nifi-state:
  minio_data:
  minio_certs:

networks:
  rede-arquivos-parquet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/29 
